name: FxAIR.org
favicon: null
layout_spectrum: 0.2387
typography_spectrum: 0.025703854858875275
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c72f32'
    - '#e5e5e5'
    - '#7c7c7c'
    - '#595959'
    - '#000000'
  brandStrength: 0.5
  lightness: 0.10597351286560297
  saturation: 0.8170156725682318
  rhythmicContrast: 0.5633587269112468
purpose: []
